name: Instruction Count Nightly Testing
on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
  create-nightly-env:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash .github/scripts/instr-count-benchmark/create-nightly-env.sh
  run-benchmark:
    needs: create-nightly-env
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash .github/scripts/instr-count-benchmark/run-benchmark.sh
  remove-nightly-env:
    needs: run-benchmark
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash .github/scripts/instr-count-benchmark/remove-nightly-env.sh
