name: Instruction Count Nightly Testing
on:
  workflow_dispatch:
jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          bash .github/scripts/instr-count-benchmark/create-nightly-env.sh
      - run: |
          bash .github/scripts/instr-count-benchmark/run-benchmark.sh
      - run: |
          bash .github/scripts/instr-count-benchmark/remove-nightly-env.sh
