name: Instruction Count Nightly Testing
on:
  workflow_dispatch:
jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create nightly env
        run: |
          bash .github/scripts/instr-count-benchmark/create-nightly-env.sh
      - name: Run Benchmark
        run: |
          bash .github/scripts/instr-count-benchmark/run-benchmark.sh
      - name: Clean up
        run: |
          bash .github/scripts/instr-count-benchmark/remove-nightly-env.sh
