name: Build PyTorch nightly docker and push to GitHub Container Registry
on:
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-docker:
    env:
      OUTPUT_DIR: $(echo ${HOME})/.torchbench/v1-nighlty-ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: main
      - run: |
          echo $OUTPUT_DIR
         

