name: pytorch-benchmarking
on: push

jobs:
  build-docker:
    runs-on: [self-hosted, bm-ec2]
    steps:
      - uses: actions/checkout@v2
      - run: bash ./scripts/build-docker.sh
  build-benchmark-docker:
    needs: build-docker
    runs-on: [self-hosted, bm-ec2]
    steps:
      - run: bash ./scripts/build-benchmark-docker.sh
  run-benchmark:
    needs: build-benchmark-docker
    runs-on: [self-hosted, bm-ec2]
    timeout-minutes: 1440
    steps:
      - run: bash ./scripts/run-docker.sh /runner/scripts/run-benchmark.sh
  upload-scribe:
    needs: run-benchmark
    runs-on: [self-hosted, bm-ec2]
    env:
      SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.SCRIBE_GRAPHQL_ACCESS_TOKEN }}
    steps:
      - run: bash ./scripts/run-docker.sh /runner/scripts/upload-scribe.sh
