name: Build PyTorch nightly docker and push to GitHub Container Registry
on:
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: main
      - uses: actions/checkout@v2
        with:
          repository: pytorch/pytorch
          ref: master
          path: pytorch
      - run: |
          export MY_FILE_PATH="abc/dev"
      - run: |
          echo $MY_FILE_PATH
          

