name: CI
on: push

jobs:
  test:
    runs-on: [self-hosted, bm-ec2]
    steps:
      - uses: actions/checkout@v2
      - run: bash ./scripts/init.sh
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark-result-${GITHUB_RUN_ID}
          path: '~/artifact-figures/figure-latest.html'
      - run: bash ./scripts/cleanup.sh
