name: Main testing workflow
on:
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-docker:
    env:
      OUTPUT_DIR: .torchbench/v1-nighlty-ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          python3 ./main.py
      - if: env.TORCHBENCH_BISECT
        run: |
           echo "Anomaly detected! Now we need to run the bisection job."
      - run: |
           echo "bisection: ${{ env.TORCHBENCH_BISECT }}"
      - name: Trigger another workflow from this one
        if: env.TORCHBENCH_BISECT
        uses: convictional/trigger-workflow-and-wait@1.3.0
        with:
          owner: xuzhao9
          repo: github-actions-prototype
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: bisection.yml
          ref: main
          propagate_failure: false
          wait_workflow: false
          inputs: ' { issue_name: "bisection_20210908+cu102" } '
      - name: Create Issue From File
        if: env.TORCHBENCH_BISECT
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Performance Signal Detected by TorchBench CI
          content-filepath: ./benchmark-result/report.md
          labels: |
            torchbench-perf-report

