name: Main testing workflow
on:
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-docker:
    env:
      OUTPUT_DIR: ~/.torchbench/v1-nighlty-ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          python3 ./main.py
      - if: env.TORCHBENCH_BISECT
        run: |
           echo "Anomaly detected! Now we need to run the bisection job."
      - run: |
           echo "bisection: ${{ env.TORCHBENCH_BISECT }}"
         

