name: Build PyTorch nightly docker and push to GitHub Container Registry
on:
  push:
    branches:
      - master
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: main
      - uses: actions/checkout@v2
        with:
          repository: pytorch/pytorch
          ref: master
          path: pytorch
      - run: |
          bash .github/scripts/publish-nightly-docker.sh

