name: Check PR body and return the content of a magic line

on:
  pull_request: 
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
    
jobs:
  detect_magic:
    if: if: ${{ contains(github.event.pull_request.body, 'RUN_TORCHBENCH:') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo ${{ github.event.pull_request.body }} > pr-body.txt
           python3 .github/scripts/generate-torchbench-filter.py --pr-body pr-body.txt
  
