name: PyTorch Release Testing
on:
  workflow_dispatch:

jobs:
  release-testing:
    runs-on: [self-hosted, reltest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: master
          path: main
      - name: Check out pytorch/examples
        uses: actions/checkout@v2
        with:
          repository: pytorch/examples
          path: examples
      - name: Install pytorch nightly
        run: |
          conda install -c pytorch-nightly pytorch torchtext torchvision torchaudio
      - name: Check machine
        run: |
          echo "Make sure the machine is tuned."
      - name: Run mnist
        run: |
          . main/.github/scripts/release-testing.env
          pushd examples/mnist
          taskset -c $CORE_LIST python main.py --epochs 1
      # - name: Run mnist hogwile
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/mnist_hogwild
      #     taskset -c $CORE_LIST python main.py --epochs 10
      # - name: Run CPU WLM LSTM
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model
      #     taskset -c $CORE_LIST python main.py --epochs 10 --model LSTM
      #  - name: Run GPU WLM LSTM
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model
      #     taskset -c $CORE_LIST python main.py --epochs 10 --model LSTM --cuda
      #  - name: Run CPU WLM Transformer
      #    run: |
      #      . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model          
      #     python main.py --epochs 10 --model Transformer
      #  - name: Run GPU WLM Transformer
      #    run: |
      #      . main/.github/scripts/release-testing.env
      #      pushd examples/word_language_model
      #      python main.py --epochs 10 --model Transformer --cuda
          
