name: PyTorch Release Testing
on:
  workflow_dispatch:

jobs:
  release-testing:
    runs-on: [self-hosted, reltest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: master
          path: main
      - name: Check out pytorch/examples
        uses: actions/checkout@v2
        with:
          repository: pytorch/examples
          path: examples
      - name: Checkout pytorch/benchmark
        uses: actions/checkout@v2
        with:
          repository: pytorch/benchmark
          path: benchmark
      - name: Create Conda env
        run: |
          conda create -y -n reltest python=3.8
      - name: Install pytorch 1.7.1
        run: |
          . activate reltest
          pip install -r main/.github/scripts/pytorch-1.7.1.txt
      - name: Check machine tuned
        run: |
          echo "Make sure the machine is tuned."
          pushd benchmark
          sudo python3 torchbenchmark/util/machine_config.py
      - name: Run MNist
        run: |
          . main/.github/scripts/release-testing.env; . activate reltest
          pushd examples/mnist
          taskset -c $CORE_LIST python main.py --epochs 1
      # - name: Run mnist hogwile
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/mnist_hogwild
      #     taskset -c $CORE_LIST python main.py --epochs 10
      # - name: Run CPU WLM LSTM
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model
      #     taskset -c $CORE_LIST python main.py --epochs 10 --model LSTM
      #  - name: Run GPU WLM LSTM
      #   run: |
      #     . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model
      #     taskset -c $CORE_LIST python main.py --epochs 10 --model LSTM --cuda
      #  - name: Run CPU WLM Transformer
      #    run: |
      #      . main/.github/scripts/release-testing.env
      #     pushd examples/word_language_model          
      #     python main.py --epochs 10 --model Transformer
      #  - name: Run GPU WLM Transformer
      #    run: |
      #      . main/.github/scripts/release-testing.env
      #      pushd examples/word_language_model
      #      python main.py --epochs 10 --model Transformer --cuda
      - name: Remove Conda env
        run: |
          conda env remove --name reltest
